[profile.default]
contracts       = 'contracts'             # The source directory
test            = 'tests'                 # The test directory
libs            = ['modules']             # A list of library directories
solc_version    = '0.8.7'                 # Override for the solc version (setting this ignores `auto_detect_solc`)
optimizer       = false                   # Enable or disable the solc optimizer
optimizer_runs  = 200                     # The number of optimizer runs
verbosity       = 3                       # The verbosity of tests
block_timestamp = 1_622_400_000              # Timestamp for tests (non-zero)
# block_timestamp = 100_000              # Timestamp for tests (non-zero)
gas_limit       = "18446744073709551615"  # Gas limit for tests

[fuzz]
runs = 1

[invariant]
runs           = 1000   # The number of calls to make in the invariant tests
depth          = 100    # The number of times to run the invariant tests
call_override  = false  # Override calls
fail_on_revert = true   # Fail the test if the contract reverts

[profile.mainnet_simulations]
test                = 'simulations/mainnet'  # The test directory
block_number        = 15320000               # Block number for tests
fork_block_number   = 15320000
rpc_storage_caching = { chains = ["mainnet"], endpoints = "all" }

[profile.local_simulations]
test = 'simulations/local'  # The test directory

[profile.deep.fuzz]
runs = 20

[profile.deep.invariant]
runs           = 1       # The number of calls to make in the invariant tests
depth          = 10_000  # The number of times to run the invariant tests
call_override  = false   # Override calls
fail_on_revert = true    # Fail the test if the contract reverts

[profile.super_deep.fuzz]
fuzz_runs = 5000

[profile.super_deep.invariant]
runs  = 10           # The number of calls to make in the invariant tests
depth = 100_000_000  # The number of times to run the invariant tests
