name: Forge Tests (PR)

on: [pull_request]

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Checkout submodules
        env:
          SSH_KEY_GLOBALS_V2: ${{secrets.SSH_KEY_GLOBALS_V2}}
          SSH_KEY_LIQUIDATIONS: ${{secrets.SSH_KEY_LIQUIDATIONS}}
          SSH_KEY_LOAN: ${{secrets.SSH_KEY_LOAN}}
          SSH_KEY_MIGRATION_HELPERS: ${{secrets.SSH_KEY_MIGRATION_HELPERS}}
          SSH_KEY_NTP: ${{secrets.SSH_KEY_NTP}}
          SSH_KEY_POOL_V2: ${{secrets.SSH_KEY_POOL_V2}}
          SSH_KEY_WITHDRAWAL_MANAGER: ${{secrets.SSH_KEY_WITHDRAWAL_MANAGER}}
        shell: bash
        run: |
          chmod +x ./scripts/setup-ci.sh
          ./scripts/setup-ci.sh

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
        run: ./scripts/test.sh -t test_

  fuzz_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Checkout submodules
        env:
          SSH_KEY_GLOBALS_V2: ${{secrets.SSH_KEY_GLOBALS_V2}}
          SSH_KEY_LIQUIDATIONS: ${{secrets.SSH_KEY_LIQUIDATIONS}}
          SSH_KEY_LOAN: ${{secrets.SSH_KEY_LOAN}}
          SSH_KEY_MIGRATION_HELPERS: ${{secrets.SSH_KEY_MIGRATION_HELPERS}}
          SSH_KEY_NTP: ${{secrets.SSH_KEY_NTP}}
          SSH_KEY_POOL_V2: ${{secrets.SSH_KEY_POOL_V2}}
          SSH_KEY_WITHDRAWAL_MANAGER: ${{secrets.SSH_KEY_WITHDRAWAL_MANAGER}}
        shell: bash
        run: |
          chmod +x ./scripts/setup-ci.sh
          ./scripts/setup-ci.sh

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
        run: ./scripts/test.sh -p deep -t testFuzz_

  invariant_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Checkout submodules
        env:
          SSH_KEY_GLOBALS_V2: ${{secrets.SSH_KEY_GLOBALS_V2}}
          SSH_KEY_LIQUIDATIONS: ${{secrets.SSH_KEY_LIQUIDATIONS}}
          SSH_KEY_LOAN: ${{secrets.SSH_KEY_LOAN}}
          SSH_KEY_MIGRATION_HELPERS: ${{secrets.SSH_KEY_MIGRATION_HELPERS}}
          SSH_KEY_NTP: ${{secrets.SSH_KEY_NTP}}
          SSH_KEY_POOL_V2: ${{secrets.SSH_KEY_POOL_V2}}
          SSH_KEY_WITHDRAWAL_MANAGER: ${{secrets.SSH_KEY_WITHDRAWAL_MANAGER}}
        shell: bash
        run: |
          chmod +x ./scripts/setup-ci.sh
          ./scripts/setup-ci.sh

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
        run: ./scripts/invariant.sh -p deep

  local_simulations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Checkout submodules
        env:
          SSH_KEY_GLOBALS_V2: ${{secrets.SSH_KEY_GLOBALS_V2}}
          SSH_KEY_LIQUIDATIONS: ${{secrets.SSH_KEY_LIQUIDATIONS}}
          SSH_KEY_LOAN: ${{secrets.SSH_KEY_LOAN}}
          SSH_KEY_MIGRATION_HELPERS: ${{secrets.SSH_KEY_MIGRATION_HELPERS}}
          SSH_KEY_NTP: ${{secrets.SSH_KEY_NTP}}
          SSH_KEY_POOL_V2: ${{secrets.SSH_KEY_POOL_V2}}
          SSH_KEY_WITHDRAWAL_MANAGER: ${{secrets.SSH_KEY_WITHDRAWAL_MANAGER}}
        shell: bash
        run: |
          chmod +x ./scripts/setup-ci.sh
          ./scripts/setup-ci.sh

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
        run: ./scripts/test.sh -p local_simulation

  mainnet_simulations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Checkout submodules
        env:
          SSH_KEY_GLOBALS_V2: ${{secrets.SSH_KEY_GLOBALS_V2}}
          SSH_KEY_LIQUIDATIONS: ${{secrets.SSH_KEY_LIQUIDATIONS}}
          SSH_KEY_LOAN: ${{secrets.SSH_KEY_LOAN}}
          SSH_KEY_MIGRATION_HELPERS: ${{secrets.SSH_KEY_MIGRATION_HELPERS}}
          SSH_KEY_NTP: ${{secrets.SSH_KEY_NTP}}
          SSH_KEY_POOL_V2: ${{secrets.SSH_KEY_POOL_V2}}
          SSH_KEY_WITHDRAWAL_MANAGER: ${{secrets.SSH_KEY_WITHDRAWAL_MANAGER}}
        shell: bash
        run: |
          chmod +x ./scripts/setup-ci.sh
          ./scripts/setup-ci.sh

      - name: Run Forge tests
        env:
          ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
        run: ./scripts/mainnet-simulation.sh
